import type React from 'react'

type LessonModule = { default: React.ComponentType }
type LessonLoader = () => Promise<LessonModule>

const lessonMap: Record<number, LessonLoader> = {
  1: () => import('../../content/lessons/en/day-01.mdx'),
  2: () => import('../../content/lessons/en/day-02.mdx'),
  3: () => import('../../content/lessons/en/day-03.mdx'),
  4: () => import('../../content/lessons/en/day-04.mdx'),
  5: () => import('../../content/lessons/en/day-05.mdx'),
  6: () => import('../../content/lessons/en/day-06.mdx'),
  7: () => import('../../content/lessons/en/day-07.mdx'),
  8: () => import('../../content/lessons/en/day-08.mdx'),
  9: () => import('../../content/lessons/en/day-09.mdx'),
  10: () => import('../../content/lessons/en/day-10.mdx'),
  11: () => import('../../content/lessons/en/day-11.mdx'),
  12: () => import('../../content/lessons/en/day-12.mdx'),
  13: () => import('../../content/lessons/en/day-13.mdx'),
  14: () => import('../../content/lessons/en/day-14.mdx'),
  15: () => import('../../content/lessons/en/day-15.mdx'),
  16: () => import('../../content/lessons/en/day-16.mdx'),
  17: () => import('../../content/lessons/en/day-17.mdx'),
  18: () => import('../../content/lessons/en/day-18.mdx'),
  19: () => import('../../content/lessons/en/day-19.mdx'),
  20: () => import('../../content/lessons/en/day-20.mdx'),
  21: () => import('../../content/lessons/en/day-21.mdx'),
  22: () => import('../../content/lessons/en/day-22.mdx'),
  23: () => import('../../content/lessons/en/day-23.mdx'),
  24: () => import('../../content/lessons/en/day-24.mdx'),
  25: () => import('../../content/lessons/en/day-25.mdx'),
  26: () => import('../../content/lessons/en/day-26.mdx'),
  27: () => import('../../content/lessons/en/day-27.mdx'),
  28: () => import('../../content/lessons/en/day-28.mdx'),
  29: () => import('../../content/lessons/en/day-29.mdx'),
  30: () => import('../../content/lessons/en/day-30.mdx'),
  31: () => import('../../content/lessons/en/day-31.mdx'),
  32: () => import('../../content/lessons/en/day-32.mdx'),
  33: () => import('../../content/lessons/en/day-33.mdx'),
  34: () => import('../../content/lessons/en/day-34.mdx'),
  35: () => import('../../content/lessons/en/day-35.mdx'),
  36: () => import('../../content/lessons/en/day-36.mdx'),
  37: () => import('../../content/lessons/en/day-37.mdx'),
  38: () => import('../../content/lessons/en/day-38.mdx'),
  39: () => import('../../content/lessons/en/day-39.mdx'),
  40: () => import('../../content/lessons/en/day-40.mdx'),
  41: () => import('../../content/lessons/en/day-41.mdx'),
  42: () => import('../../content/lessons/en/day-42.mdx'),
  43: () => import('../../content/lessons/en/day-43.mdx'),
  44: () => import('../../content/lessons/en/day-44.mdx'),
  45: () => import('../../content/lessons/en/day-45.mdx'),
  46: () => import('../../content/lessons/en/day-46.mdx'),
  47: () => import('../../content/lessons/en/day-47.mdx'),
  48: () => import('../../content/lessons/en/day-48.mdx'),
  49: () => import('../../content/lessons/en/day-49.mdx'),
  50: () => import('../../content/lessons/en/day-50.mdx'),
  51: () => import('../../content/lessons/en/day-51.mdx'),
  52: () => import('../../content/lessons/en/day-52.mdx'),
  53: () => import('../../content/lessons/en/day-53.mdx'),
  54: () => import('../../content/lessons/en/day-54.mdx'),
  55: () => import('../../content/lessons/en/day-55.mdx'),
  56: () => import('../../content/lessons/en/day-56.mdx'),
}

export function getLessonLoader(id: number): LessonLoader | undefined {
  return lessonMap[id]
}
